* Higher level control of SynthDefs

#+BEGIN_SRC supercollider
(
SynthDef(\blip, {|out = 0, amp = 0.6, dur = 1, freq = 1|
	var sig, env;
	env = EnvGen.kr(Env.perc(0.01, dur), doneAction:2); //take care of doneAction!
	sig = SinOsc.ar([120.0, 121.0] * freq); //two output sine oscillator synth.
	sig = sig / 2;
	Out.ar(out, sig * amp * env); //out creates a buss.
}).add;
)

(
SynthDef(\crackle, {|out = 0, chaos = 1.5, amp = 0.6, envDur = 0.3|
	var env, sig;
	env = EnvGen.kr(Env.sine(envDur), doneAction:2);
	sig = Crackle.ar(chaos, 0.5, 0.5);
	sig = sig.dup / 2; //duplicating the signal so it plays in both channels.
	Out.ar(out, sig * amp * env);
}).add;
)
#+END_SRC 

Create instances of the above SynthDefs using another class named Synth. In the Synth class we may change the arguments and give new values to its parameters.
#+BEGIN_SRC supercollider
x = Synth(\blip, [\amp, 0.4, \out, 0, \dur, 1.0.rand]); //create an instance of 'drony' and assign it on a global var 'x'
y = Synth(\sawy, [\amp, 0.4, \out, 0, \dur, 10, \speed, 10]); //create an instance of 'saw' and assign it on a global var 'y'
#+END_SRC

We can also control the SynthDefs using ~set~ method: ~x.set(\dur, 0.25);~

** Events, streams and patterns.
Patterns in SuperCollider are streams of values that can be updated /on the
fly/. Providing an appropriate mapping these can be assigned to the parameters
of the SynthDefs in order to manipulate the sound outcome in real time.
SuperCollider provides a wealth of patterns which implement random to sequential distribution of values.

#+BEGIN_SRC supercollider
a = Pseq([1, 2, 3, 4], inf).asStream; //sequence of values from 1 to 4.
a.next; //run the sequence using. .next method.
#+END_SRC

#+RESULTS:

*** Using a Pbind to control the SynthDefs.
Pbind is a wrapper for Events in SuperCollider. 
#+BEGIN_SRC sclang
Pbind(\type, \happyEvent, \degree, Pseq([0, 1, 2, 3, 4, 4, 5, 5, 5, 5, 4, 2, 3, 2, 3, 1], inf), \dur, Pwhite(0.1, 1.0, inf)).play; ); //Evaluate this line.
#+END_SRC

It takes couple of standard
arguments that are needed for the Pbind, such as duration and name of the SynthDef, denoted by a prefix
~\instrument~, for example to control the blip SynthDef we do it like this:
~\instrument, \blip~. The Pbind may have all or some arguments contained in the
SynthDef or just the ones we are trying to interact with.

**** Pbind example 
#+BEGIN_SRC supercollider
Pbind(\instrument, \blip, \dur, 0.25, \freq, 1).play;
Pbind(\instrument, \blip, \dur, 0.25, \freq, 2).play; 
Pbind(\instrument, \blip, \dur, 0.5, \freq, 0.5).play;


Pbind(\instrument, \sawy, \dur, 0.1, \speed, 2, \freq, 3).play;
Pbind(\instrument, \sawy, \dur, 0.01, \speed, 2, \freq, 1).play;
#+END_SRC

To change something without stopping the sound use a Pdef.
**** Pdef example
#+BEGIN_SRC supercollider
Pdef(\x).play;
Pdef(\x,  Pbind(\instrument, \crackle, \dur, 2));
Pdef(\x, Pbind(\instrument, \crackle, \chaos, Pwhite(0.1, 2.0, inf),  \envDur, 0.3, \dur, 0.08));
#+END_SRC

***** ...and change things 'on the fly'
#+BEGIN_SRC supercollider
Pdef(\y, Pbind(\instrument, \blip, \dur, Pbrown(0, 6, 0.1, inf), \freq, 2));
Pdef(\y).play;
Pdef(\x).stop;
Pdef(\y).stop;
#+END_SRC

#+RESULTS:

** Discussion
Patterns are used to control SynthDefs in a higher level; SuperCollider provides
a lot of pattern implementations, including sequential and random generators.
Using them one can create various sonic and musical gestures which can be used
as boiler code for live improvisation and/or generate audio material for fixed
media composition. Thus, patterns are very powerful interface to interact with
various SynthDefs and can act as a very expressive tool for laptop improvisation
with SuperCollider.

** Assignment
Create couple of SynthDefs and control them with Pdef and Pbind assigning
different patterns on SynthDef parameters.
