* Semester Assignment Audio Programming Class

** Make a system that allows you to perform live, or synthesize sounds for a larger scale piece.

For this system you may use things from the repository and material such as demos & examples we have developed during our classes, using: SynthDefs.

** Things to consider while developing the system:

+ Functionality
+ Interactivity
+ Extendability
+ _musicality/artistic usability_

** Delivery requirements:
A video of the project not less than 3' to 7' which shows that the system is working and is controlable. A brief explanation of the system describing your goals and how it works, weaknesses of the system, and future directions between 150 and 300 words, with references and relevant links mentioned accordingly if available. In case you have copied code from somewhere it is ethical and good practice to mention that in the text. The project should not be something that exceeds the knowledge you have acquired, and thus, you must be able to discuss the code and possibly reproduce, in case it is required, so not safari code in the web to impress others...

*** Deadline: not later than 18th of June.
***  Please add this project in the google drive folder (including all assignments/mid-semester) named Final Project, after deadline bets are off.
