b = "will I exist after recompile SC?"

(
  var apple = "I am a red apple";
var b = "do I work";
apple ++ " " ++ b;
)

(
  var apple;
  apple.postln
 )

(
var apple = "big apple";
var appleColor = "red, and juicy";
("I am a " ++ apple ++ " " ++ appleColor);
)

b = "something"; //global; can be used anywhere inside the program.

(
var a = 1;
var b = 2;
var sum = a * b;
sum
)

(
var lorem = "lorem ipsum dolor sit amet",
ipsum = "consectetur adipisicing elit";
lorem ++ " " ++ ipsum
 )